# Generated by Django 3.0.4 on 2020-03-12 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.PositiveSmallIntegerField(choices=[(0, 'photo'), (1, 'video')])),
                ('path', models.CharField(max_length=255)),
                ('valide', models.BooleanField()),
                ('mobileuserid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.MobileUser')),
                ('moderatorid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Moderator')),
            ],
        ),
    ]
