# Generated by Django 3.0.4 on 2020-04-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_id',
            field=models.IntegerField(null=True),
        ),
    ]
