# Generated by Django 3.0.4 on 2020-04-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
