# Generated by Django 3.0.4 on 2020-03-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200323_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentarticle',
            name='path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
