# Generated by Django 3.0.4 on 2020-05-15 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200327_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentarticle',
            name='articleid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.Article'),
        ),
    ]
