# Generated by Django 3.0.4 on 2020-05-15 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200403_1106'),
        ('articles', '0004_auto_20200515_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='moderatorid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Moderator'),
        ),
    ]
