language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
env:
  global:
  - DJANGO_SETTINGS_MODULE="coronawatch.settings"
  - HEROKU_API_KEY="aff0a1f6-1592-4f64-9e4e-5c2834fcd9c4"
  - HEROKU_APP_APP="coronawatch"

services:
- postgresql
- docker
before_install:
- docker-compose build
script:
- echo "Starting tests"
- docker-compose run web sh -c "python manage.py test"
deploy:
  provider: script
  script:
    docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  on:
     branch: master