language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
env:
  global:
  - DJANGO_SETTINGS_MODULE="coronawatch.settings"
  - HEROKU_API_KEY="68757907-7f23-4219-83d8-4edf6b94a13d"
  - HEROKU_APP_APP="coronawatch"

services:
- postgresql
- docker
before_install:
- psql -c 'create database coronawatch;' -U postgres
- docker-compose build
script:
- echo "Starting tests"
- python manage.py test
- docker-compose run web sh -c "python manage.py test"
deploy:
  provider: script
  script:
    docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com;
    heroku container:push web --app coronawatch;
    heroku container:release web --app coronawatch;
    heroku run python manage.py migrate --app coronawatch
  on:
     branch: master
