# Generated by Django 3.0.4 on 2020-03-12 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('articleid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Article')),
                ('mobileuserid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='users.MobileUser')),
            ],
        ),
        migrations.CreateModel(
            name='attachmentArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.PositiveSmallIntegerField(choices=[(0, 'photo'), (1, 'video')])),
                ('path', models.CharField(max_length=255)),
                ('articleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='articles.Article')),
            ],
        ),
    ]
