# Generated by Django 3.0.4 on 2020-03-12 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.PositiveSmallIntegerField(choices=[(0, 'FACEBOOK'), (1, 'YOUTUBE'), (2, 'WEB')])),
                ('url', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('valide', models.BooleanField()),
                ('moderatorid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Moderator')),
            ],
        ),
        migrations.CreateModel(
            name='commentRobotsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('mobileuserid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MobileUser')),
                ('robotcontentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='robots.RobotsContent')),
            ],
        ),
    ]
