# Generated by Django 3.0.4 on 2020-03-27 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotscontent',
            name='moderatorid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Moderator'),
        ),
        migrations.AddField(
            model_name='commentrobotscontent',
            name='mobileuserid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MobileUser'),
        ),
        migrations.AddField(
            model_name='commentrobotscontent',
            name='robotcontentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='robots.RobotsContent'),
        ),
    ]
