# Generated by Django 3.0.4 on 2020-06-08 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200403_1106'),
        ('robots', '0002_auto_20200323_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrobotscontent',
            name='robotcontentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='robots.RobotsContent'),
        ),
        migrations.AlterField(
            model_name='robotscontent',
            name='moderatorid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Moderator'),
        ),
        migrations.AlterField(
            model_name='robotscontent',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
