# Generated by Django 3.0.4 on 2020-03-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.PositiveSmallIntegerField(choices=[(0, 'photo'), (1, 'video')])),
                ('path', models.CharField(max_length=255)),
                ('valide', models.BooleanField()),
            ],
        ),
    ]
