# Generated by Django 3.0.3 on 2020-03-23 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='mobileuserid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.MobileUser'),
        ),
        migrations.AddField(
            model_name='reports',
            name='moderatorid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Moderator'),
        ),
    ]
