# Generated by Django 3.0.4 on 2020-05-21 16:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200403_1106'),
        ('reporting', '0002_auto_20200323_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reports',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='other_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='attachment_type',
            field=models.CharField(choices=[('photo', 'photo'), ('video', 'video')], max_length=5),
        ),
        migrations.AlterField(
            model_name='reports',
            name='moderatorid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Moderator'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
