# Generated by Django 3.0.4 on 2020-05-20 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200403_1106'),
        ('videosHomePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentthematicvideo',
            name='mobileuserid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videoscomments', to='users.MobileUser'),
        ),
        migrations.AlterField(
            model_name='commentthematicvideo',
            name='thematicVideoid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videosHomePage.thematicVideo'),
        ),
        migrations.AlterField(
            model_name='thematicvideo',
            name='moderatorid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Moderator'),
        ),
        migrations.AlterField(
            model_name='thematicvideo',
            name='path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thematicvideo',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
