# Generated by Django 3.0.4 on 2020-05-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosHomePage', '0002_auto_20200520_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thematicvideo',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
