# Generated by Django 3.0.4 on 2020-03-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regions',
            options={'managed': True},
        ),
    ]
