# Generated by Django 3.0.4 on 2020-03-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20200312_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regions',
            options={'managed': False},
        ),
    ]
