# Generated by Django 3.0.4 on 2020-03-27 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regions',
            name='riskagentid',
            field=models.ForeignKey(blank=True, db_column='riskagentid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Agent'),
        ),
        migrations.AddField(
            model_name='regions',
            name='riskmoderatorid',
            field=models.ForeignKey(blank=True, db_column='riskmoderatorid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Moderator'),
        ),
        migrations.AddField(
            model_name='receptioncenter',
            name='regionid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geo.Regions'),
        ),
        migrations.AddField(
            model_name='infectedregions',
            name='agentid',
            field=models.ForeignKey(blank=True, db_column='riskagentid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Agent'),
        ),
        migrations.AddField(
            model_name='infectedregions',
            name='moderatorid',
            field=models.ForeignKey(blank=True, db_column='riskmoderatorid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Moderator'),
        ),
        migrations.AddField(
            model_name='infectedregions',
            name='regionid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geo.Regions'),
        ),
    ]
