# Generated by Django 3.0.4 on 2020-03-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20200323_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptioncenter',
            name='name',
        ),
    ]
