# Generated by Django 3.0.4 on 2020-03-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_remove_receptioncenter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptioncenter',
            name='name',
            field=models.CharField(default='d', max_length=255),
            preserve_default=False,
        ),
    ]
