# Generated by Django 3.0.4 on 2020-04-01 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('geo', '0004_receptioncenter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='infectedregions',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='infectedregions',
            name='nb_confirmed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infectedregions',
            name='nb_notyetsick',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infectedregions',
            name='nb_suspected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='infectedregions',
            name='agentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Agent'),
        ),
        migrations.AlterField(
            model_name='infectedregions',
            name='moderatorid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Moderator'),
        ),
        migrations.AlterField(
            model_name='infectedregions',
            name='regionid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geo.Regions'),
        ),
        migrations.AlterField(
            model_name='infectedregions',
            name='valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='regions',
            name='riskagentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Agent'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='riskmoderatorid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Moderator'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='riskvalide',
            field=models.BooleanField(default=False),
        ),
    ]
