# Generated by Django 3.0.4 on 2020-04-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_auto_20200401_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='riskvalide',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
