# Generated by Django 3.0.4 on 2020-04-01 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_auto_20200401_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infectedregions',
            name='regionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='geo.Regions'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='regions', to='geo.Countries'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='riskregion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='regions',
            name='riskvalide',
            field=models.BooleanField(default=False),
        ),
    ]
