# Generated by Django 3.0.4 on 2020-04-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0010_auto_20200401_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infectedregions',
            name='lastUpdated',
        ),
    ]
