# Generated by Django 3.0.4 on 2020-04-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_remove_infectedregions_lastupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infectedregions',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
