# Generated by Django 3.0.4 on 2020-05-15 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200403_1106'),
        ('geo', '0014_auto_20200505_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infectedregions',
            name='moderatorid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Moderator'),
        ),
        migrations.AlterField(
            model_name='infectedregions',
            name='regionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='geo.Regions'),
        ),
        migrations.AlterField(
            model_name='receptioncenter',
            name='regionid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Regions'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='geo.Countries'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='riskagentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Agent'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='riskmoderatorid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Moderator'),
        ),
    ]
