# Generated by Django 3.0.4 on 2020-03-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAnalyze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('mobileuserid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photoanalyse', to='users.MobileUser')),
            ],
        ),
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('temperature', models.CharField(max_length=255)),
                ('heartbeat', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('mobileuserid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthinfos', to='users.MobileUser')),
            ],
        ),
    ]
