# Generated by Django 3.0.3 on 2020-03-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoanalyze',
            name='path',
        ),
    ]
