# Generated by Django 3.0.3 on 2020-03-23 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoanalyze',
            name='mobileuserid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photoanalyse', to='users.MobileUser'),
        ),
        migrations.AddField(
            model_name='healthinfo',
            name='mobileuserid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthinfos', to='users.MobileUser'),
        ),
    ]
